In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv('../data/위험성 평가 정보_2021년.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11304 entries, 0 to 11303
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ﻿ACDNT_RISK_ASM_UQNUM     11304 non-null  int64
 1   ACDNT_RISK_ASM_NO         11304 non-null  int64
 2   PIPE_NO                   11304 non-null  int64
 3   CO_INFO                   11304 non-null  object
 4   ACDNT_TYPE                11304 non-null  object
 5   ACDNT_DMGE_TYPE           11304 non-null  object
 6   DMGE_ARA_CRTR_DGDGR       11304 non-null  float64
 7   DMGE_ARA_CRTR_DGDGR_RANK  5652 non-null   object
 8   DPRS_CRTR_DMGE_FQ         11304 non-null  float64
 9   DPRS_CRTR_DMGE_SCALE      11304 non-null  int64
 10  DPRS_CRTR_DGDGR           11304 non-null  float64
 11  DPRS_CRTR_DGDGR_RANK      5652 non-null   object
 12  PIPE_DIA                  11304 non-null  int64
 13  PIPE_LT                   11304 non-null  float64
 14  PIPE_MATR_CODE            11304 non-null  int64
 15  PIPE_COAT_MATR_CODE       11304 non-null  int64
 16  PIPE_DESGN_THICKNESS      11304 non-null  float64
 17  PIPE_OPRT_TP              11304 non-null  int64
 18  PIPE_INNER_FUD_STA_CODE   11304 non-null  int64
 19  MATR_CODE                 11304 non-null  int64
 20  PIPE_PRESSURE             11304 non-null  object
 21  PIPE_FLRT                 11304 non-null  object
 22  PIPE_INSTL_YEAR           11304 non-null  int64
dtypes: float64(5), int64(11), object(7)
memory usage: 2.0+ MB

In [6]:
df

,﻿ACDNT_RISK_ASM_UQNUM,ACDNT_RISK_ASM_NO,PIPE_NO,CO_INFO,ACDNT_TYPE,ACDNT_DMGE_TYPE,DMGE_ARA_CRTR_DGDGR,DMGE_ARA_CRTR_DGDGR_RANK,DPRS_CRTR_DMGE_FQ,DPRS_CRTR_DMGE_SCALE,...,PIPE_LT,PIPE_MATR_CODE,PIPE_COAT_MATR_CODE,PIPE_DESGN_THICKNESS,PIPE_OPRT_TP,PIPE_INNER_FUD_STA_CODE,MATR_CODE,PIPE_PRESSURE,PIPE_FLRT,PIPE_INSTL_YEAR
0,1,1,110,회사1,rupture,TOXIC,0.000000,하,0.000000e+00,0,...,0.00,1,2,0.00,0,2,1,"{0,0)","{0,0)",0
1,2,1,110,회사1,rupture,RADIATION,0.772762,중,0.000000e+00,0,...,0.00,1,2,0.00,0,2,1,"{0,0)","{0,0)",0
2,3,1,110,회사1,rupture,EXPLOSION,0.000000,하,0.000000e+00,0,...,0.00,1,2,0.00,0,2,1,"{0,0)","{0,0)",0
3,4,1,110,회사1,hole,TOXIC,0.000000,하,0.000000e+00,0,...,581.09,1,2,8.18,10,2,1,"{30,40)","{0,10)",1991
4,5,1,110,회사1,hole,RADIATION,1.187132,중,0.000000e+00,0,...,207.69,1,2,8.18,10,2,1,"{30,40)","{0,10)",1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11299,11300,110,500682,회사10,hole,HIGH,0.088100,중,0.000000e+00,0,...,2296.95,1,2,7.11,30,2,10,"{10,20)","{120,130)",1996
11300,11301,110,500682,회사10,pinhole,HIGH,0.000000,하,0.000000e+00,0,...,2296.95,1,2,7.11,30,2,10,"{10,20)","{120,130)",1996
11301,11302,110,500682,회사10,rupture,HIGH,0.000000,NaN,3.520000e-07,2,...,2296.95,1,2,7.11,30,2,10,"{10,20)","{120,130)",1996
11302,11303,110,500682,회사10,hole,HIGH,0.000000,NaN,3.730000e-06,1,...,262.67,1,2,7.11,30,2,10,"{10,20)","{120,130)",1996
11303,11304,110,500682,회사10,pinhole,HIGH,0.000000,NaN,2.940000e-08,1,...,650.83,1,2,7.11,30,2,10,"{10,20)","{120,130)",1996

In [16]:
df=df.rename(columns={'ACDNT_DMGE_TYPE':'사고피해유형'})

In [15]:
df=df.rename(columns={'ACDNT_TYPE':'사고유형'})

In [17]:
df

,﻿ACDNT_RISK_ASM_UQNUM,ACDNT_RISK_ASM_NO,PIPE_NO,CO_INFO,사고유형,사고피해유형,DMGE_ARA_CRTR_DGDGR,DMGE_ARA_CRTR_DGDGR_RANK,DPRS_CRTR_DMGE_FQ,DPRS_CRTR_DMGE_SCALE,...,PIPE_LT,PIPE_MATR_CODE,PIPE_COAT_MATR_CODE,PIPE_DESGN_THICKNESS,PIPE_OPRT_TP,PIPE_INNER_FUD_STA_CODE,MATR_CODE,PIPE_PRESSURE,PIPE_FLRT,PIPE_INSTL_YEAR
0,1,1,110,회사1,rupture,TOXIC,0.000000,하,0.000000e+00,0,...,0.00,1,2,0.00,0,2,1,"{0,0)","{0,0)",0
1,2,1,110,회사1,rupture,RADIATION,0.772762,중,0.000000e+00,0,...,0.00,1,2,0.00,0,2,1,"{0,0)","{0,0)",0
2,3,1,110,회사1,rupture,EXPLOSION,0.000000,하,0.000000e+00,0,...,0.00,1,2,0.00,0,2,1,"{0,0)","{0,0)",0
3,4,1,110,회사1,hole,TOXIC,0.000000,하,0.000000e+00,0,...,581.09,1,2,8.18,10,2,1,"{30,40)","{0,10)",1991
4,5,1,110,회사1,hole,RADIATION,1.187132,중,0.000000e+00,0,...,207.69,1,2,8.18,10,2,1,"{30,40)","{0,10)",1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11299,11300,110,500682,회사10,hole,HIGH,0.088100,중,0.000000e+00,0,...,2296.95,1,2,7.11,30,2,10,"{10,20)","{120,130)",1996
11300,11301,110,500682,회사10,pinhole,HIGH,0.000000,하,0.000000e+00,0,...,2296.95,1,2,7.11,30,2,10,"{10,20)","{120,130)",1996
11301,11302,110,500682,회사10,rupture,HIGH,0.000000,NaN,3.520000e-07,2,...,2296.95,1,2,7.11,30,2,10,"{10,20)","{120,130)",1996
11302,11303,110,500682,회사10,hole,HIGH,0.000000,NaN,3.730000e-06,1,...,262.67,1,2,7.11,30,2,10,"{10,20)","{120,130)",1996
11303,11304,110,500682,회사10,pinhole,HIGH,0.000000,NaN,2.940000e-08,1,...,650.83,1,2,7.11,30,2,10,"{10,20)","{120,130)",1996

In [19]:
df.describe()

,﻿ACDNT_RISK_ASM_UQNUM,ACDNT_RISK_ASM_NO,PIPE_NO,DMGE_ARA_CRTR_DGDGR,DPRS_CRTR_DMGE_FQ,DPRS_CRTR_DMGE_SCALE,DPRS_CRTR_DGDGR,PIPE_DIA,PIPE_LT,PIPE_MATR_CODE,PIPE_COAT_MATR_CODE,PIPE_DESGN_THICKNESS,PIPE_OPRT_TP,PIPE_INNER_FUD_STA_CODE,MATR_CODE,PIPE_INSTL_YEAR
count,11304.000000,11304.000000,11304.000000,11304.000000,1.130400e+04,11304.000000,1.130400e+04,11304.000000,11304.000000,11304.0,11304.0,11304.000000,11304.000000,11304.000000,11304.000000,11304.000000
mean,5652.500000,47.664544,430029.527601,0.251931,9.489381e-07,2.200991,4.047144e-06,120.233546,732.589108,1.0,2.0,7.289660,18.830149,1.853503,5.590234,1954.520170
std,3263.328056,35.522296,358220.813802,1.586487,3.661475e-06,10.952348,2.249765e-05,37.937379,678.230241,0.0,0.0,5.414575,6.120859,0.353619,2.630139,257.094155
min,1.000000,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,1.0,2.0,0.000000,0.000000,1.000000,1.000000,0.000000
25%,2826.750000,17.000000,836.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,100.000000,336.700000,1.0,2.0,5.900000,20.000000,2.000000,3.000000,1979.000000
50%,5652.500000,41.000000,500305.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,100.000000,478.130000,1.0,2.0,6.020000,20.000000,2.000000,6.000000,1986.000000
75%,8478.250000,75.000000,820203.000000,0.010889,1.920000e-07,1.000000,2.470000e-07,150.000000,1065.500000,1.0,2.0,7.100000,20.000000,2.000000,7.000000,1996.000000
max,11304.000000,150.000000,830253.000000,23.754793,4.140000e-05,180.000000,4.036980e-04,200.000000,3367.910000,1.0,2.0,40.000000,40.000000,2.000000,10.000000,2008.000000

TypeError: 'DataFrameGroupBy' object is not callable